# Generated by Django 6.0.4 on 2026-04-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='_grade',
            field=models.TextField(blank=True, db_column='grade', null=True),
        ),
    ]
